### ISSUE TITLE
DynHost isn’t updated automatically

### ISSUE THREAD

**Issue by non092** [GuilleGF/hassio-ovh#1]
I started using your integration yesterday as I was looking to setup external acces to HA and prefer using the domain I already own at OVH then something like DuckDNS
However it doesn’t seem like the DynHost get updated correctly when my public IP changes. I’ve looked at the code and my understanding is that it should get updated every 5 minutes ?
The DynHost gets correctly updated if I restart HA

**Comment by Loweack** [comment]
Same for me, it didn't. I had to do it manually via the OVH interface.

**Comment by GuilleGF** [comment]
Fixed in release 2.0.0
