### ISSUE TITLE
Missing version in manifest

### ISSUE THREAD

**Issue by guillaumebignon** [GuilleGF/hassio-ovh#4]
Message in  Ha logs :
`No 'version' key in the manifest file for custom integration 'ovh'. As of Home Assistant 2021.6, this integration will no longer be loaded. Please report this to the maintainer of 'ovh'`

**Comment by GuilleGF** [comment]
Added in 1.1.0 released https://github.com/GuilleGF/hassio-ovh/releases/tag/1.1.0
